# Generated by Django 4.2.1 on 2023-07-18 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('stock', models.IntegerField()),
                ('purchase_value', models.FloatField()),
                ('sale_value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart_creation_date', models.DateField(auto_now_add=True)),
                ('cart_status', models.CharField(max_length=20)),
                ('product', models.ManyToManyField(blank=True, to='products_and_services.products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_and_services.categories'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_rating',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products_and_services.product_rating'),
        ),
    ]
