# Generated by Django 4.2.1 on 2023-07-18 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_services', '0002_product_rating_products_categories_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_rating',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='products_and_services.product_rating'),
        ),
    ]
