# Generated by Django 4.2.1 on 2023-07-19 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_services', '0004_alter_products_product_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shopping_Cart',
        ),
    ]
