# Generated by Django 4.2.1 on 2023-07-19 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_services', '0005_delete_shopping_cart'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Methods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Promo_Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('percentage', models.FloatField()),
                ('code_status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=30)),
                ('device', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('attachments', models.FileField(upload_to=None)),
                ('cart_creation_date', models.DateField(auto_now_add=True)),
                ('work_status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.FloatField()),
                ('cart_creation_date', models.DateField(auto_now_add=True)),
                ('cart_status', models.CharField(max_length=20)),
                ('product', models.ManyToManyField(blank=True, to='products_and_services.products')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_creation_date', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=15)),
                ('payment_methods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.payment_methods')),
                ('promo_codes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.promo_codes')),
                ('shopping_cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='processes.shopping_cart')),
            ],
        ),
    ]
