# Generated by Django 4.2.1 on 2023-07-19 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_payment_methods_promo_codes_work_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_status', models.CharField(max_length=15)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='processes.purchase_orders')),
            ],
        ),
    ]
