# Generated by Django 4.2.1 on 2023-07-19 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('processes', '0003_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_orders',
            name='shipping_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.shipping_address'),
            preserve_default=False,
        ),
    ]
